-- Create accounts table
CREATE TABLE IF NOT EXISTS accounts_customuser (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    role ENUM('admin', 'user') DEFAULT 'user',
    status ENUM('active', 'disabled') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create inventory tables
CREATE TABLE IF NOT EXISTS inventory_asset (
    id INT AUTO_INCREMENT PRIMARY KEY,
    asset_name VARCHAR(255) NOT NULL,
    hostname VARCHAR(255),
    ip_address VARCHAR(45),
    asset_type ENUM('web-server', 'database', 'vm', 'other') DEFAULT 'other',
    criticality ENUM('low', 'medium', 'high', 'critical') DEFAULT 'medium',
    environment VARCHAR(50),
    owner_id INT,
    FOREIGN KEY (owner_id) REFERENCES accounts_customuser(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS inventory_agent (
    id INT AUTO_INCREMENT PRIMARY KEY,
    asset_id INT,
    wazuh_agent_id VARCHAR(50) UNIQUE,
    status ENUM('active', 'disconnected', 'never_connected') DEFAULT 'never_connected',
    last_seen TIMESTAMP,
    FOREIGN KEY (asset_id) REFERENCES inventory_asset(id) ON DELETE CASCADE
);

-- Create SOC tables
CREATE TABLE IF NOT EXISTS soc_alertreference (
    id INT AUTO_INCREMENT PRIMARY KEY,
    wazuh_doc_id VARCHAR(255) UNIQUE,
    rule_id INT,
    severity INT,
    title VARCHAR(255),
    agent_name VARCHAR(255),
    source_ip VARCHAR(45),
    occurred_at TIMESTAMP,
    acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_by_id INT,
    FOREIGN KEY (acknowledged_by_id) REFERENCES accounts_customuser(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS soc_incident (
    id INT AUTO_INCREMENT PRIMARY KEY,
    incident_number VARCHAR(50) UNIQUE,
    title VARCHAR(255),
    description TEXT,
    priority ENUM('low', 'medium', 'high', 'critical') DEFAULT 'medium',
    status ENUM('open', 'in_progress', 'resolved', 'closed') DEFAULT 'open',
    created_by_id INT,
    assigned_to_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by_id) REFERENCES accounts_customuser(id) ON DELETE SET NULL,
    FOREIGN KEY (assigned_to_id) REFERENCES accounts_customuser(id) ON DELETE SET NULL
);

-- Insert initial admin user (Password: SecurePass123! - hashed needs to be generated by app, inserting placeholder for now but manual update might be needed or seed script)
-- For now, we will rely on a python script to create the admin user to ensure correct hashing.
